# Generated by Django 3.0.2 on 2020-02-27 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('age', models.IntegerField(max_length=3)),
                ('bdate', models.DateField(verbose_name='birthdate')),
                ('hobby', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('p_name', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField(max_length=10)),
                ('email_id', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoldBooks',
            fields=[
                ('b_ISBN', models.IntegerField(max_length=13)),
                ('b_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('b_author', models.CharField(max_length=40)),
                ('b_price', models.FloatField()),
                ('b_pubyear', models.IntegerField(max_length=4)),
                ('b_category', models.CharField(default='', max_length=20)),
                ('buyer_name', models.CharField(max_length=30)),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.User')),
            ],
        ),
        migrations.CreateModel(
            name='AvailBooks',
            fields=[
                ('b_ISBN', models.IntegerField(max_length=13)),
                ('b_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('b_author', models.CharField(max_length=40)),
                ('b_price', models.FloatField()),
                ('b_pubyear', models.IntegerField(max_length=4)),
                ('b_category', models.CharField(max_length=20)),
                ('uploader_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.User')),
            ],
        ),
    ]
