# Generated by Django 3.0.2 on 2020-03-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availbooks',
            name='b_pubyear',
        ),
        migrations.RemoveField(
            model_name='soldbooks',
            name='b_pubyear',
        ),
        migrations.AddField(
            model_name='availbooks',
            name='b_photo',
            field=models.ImageField(default='', upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='availbooks',
            name='b_publisher',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='soldbooks',
            name='b_photo',
            field=models.ImageField(default='', upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='soldbooks',
            name='b_publisher',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='availbooks',
            name='uploader_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.User'),
        ),
    ]
