# Generated by Django 3.0.2 on 2020-03-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200308_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availbooks',
            name='b_ISBN',
            field=models.IntegerField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='availbooks',
            name='b_publisher',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='soldbooks',
            name='b_ISBN',
            field=models.IntegerField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='soldbooks',
            name='b_publisher',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='soldbooks',
            name='buyer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.User'),
        ),
        migrations.AlterField(
            model_name='soldbooks',
            name='seller_name',
            field=models.CharField(max_length=30),
        ),
    ]
