# Generated by Django 3.0.2 on 2020-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200308_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availbooks',
            name='b_ISBN',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='availbooks',
            name='b_photo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='soldbooks',
            name='b_ISBN',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='soldbooks',
            name='b_photo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
