# Generated by Django 3.0.2 on 2020-03-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200309_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='availbooks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldbooks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availbooks',
            name='b_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='soldbooks',
            name='b_name',
            field=models.CharField(max_length=50),
        ),
    ]
