# Generated by Django 3.0.2 on 2020-03-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200311_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='availbooks',
            name='b_description',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='availbooks',
            name='bdate',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='soldbooks',
            name='b_description',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='soldbooks',
            name='bdate',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
