# Generated by Django 3.0.2 on 2020-03-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200311_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availbooks',
            name='bdate',
        ),
        migrations.RemoveField(
            model_name='soldbooks',
            name='bdate',
        ),
    ]
