# Generated by Django 3.0.2 on 2020-03-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20200311_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldbooks',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Solddate'),
        ),
        migrations.AlterField(
            model_name='soldbooks',
            name='buyer_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='soldbooks',
            name='seller_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.User'),
        ),
    ]
